##################################################################
# +------------------------------------------------------------+ #
# |                   qGP-ClaimBlocks Config                   | #
# |   Source:   https://github.com/QarthO/qGP-ClaimBlocks/     | #
# |   Download: https://modrinth.com/plugin/qGP-ClaimBlocks/   | #
# |   Donate:   https://quartzdev.gg/donate/                   | #
# |   Discord:  https://quartzdev.gg/discord/                  | #
# +------------------------------------------------------------+ #
# Default Config
schema-version: 1.0

# Requires 'q.gpcb.admin.updates' permission to be notified
# OPs can deny this permission to not be notified upon logging in
# Only checks when the server boots or someone with the permission logs in
# Note: A server restart is required to change this setting
# Default: true
check-updates: true

##################################################################
# +------------------------------------------------------------+ #
# |                          Withdraw                          | #
# +------------------------------------------------------------+ #
##################################################################

# requires permission: 'q.gpcb.command.withdraw'
withdraw:
  # The minimum amount of blocks a player can withdraw into a deposit slip
  # Bypass with permission: 'q.gpcb.command.withdraw.min.bypass'
  # Override with permission:'q.gpcb.withdraw.min.<amount>'
  # Default: 100 || Range: 0 - 2147483647 || Use '-1' to disable
  min-claim-blocks: 100

  # The maxmimum amount of blocks a player can withdraw into a deposit slip
  # Bypass with permission: 'q.gpcb.withdraw.max.bypass'
  # Override with permission:'q.gpcb.withdraw.max.<amount>'
  # Default: -1 || Range: 1 - 2147483647 || Use '-1' to disable
  max-claim-blocks: -1

  # Full customization over the deposit slip item(aka voucher)
  # Full material list: https://jd.papermc.io/paper/1.20/org/bukkit/Material.html
  # Supports MiniMessage format: https://docs.advntr.dev/minimessage/format.html
  # To have no lore, use: ... lore: []
  # Default:
  #   deposit-slip:
  #     material: PAPER
  #     name: <yellow><bold><blocks> Claim Blocks
  #     lore:
  #     - '<blue>Claimblocks: <green><blocks>'
  #     - '<blue>Withdrawer: <green><withdrawer>'
  #     - '<blue>Slip ID: <green><id>'
  deposit-slip:
    material: PAPER
    name: <yellow><bold><blocks> Claim Blocks
    lore:
      - '<blue>Claimblocks: <green><blocks>'
      - '<blue>Withdrawer: <green><withdrawer>'
      - '<blue>Slip ID: <green><id>'

##################################################################
# +------------------------------------------------------------+ #
# |                          Transfer                          | #
# +------------------------------------------------------------+ #
##################################################################

# requires permission: 'q.gpcb.command.transfer'
transfer:
  # The minimum amount of blocks a player can send
  # Bypass with permission: 'q.gpcb.transfer.min.bypass'
  # Override with permission:'q.gpcb.transfer.min.<amount>'
  # Default: 100 || Range: 0 - 2147483647
  min-claim-blocks: 1

  # The maxmimum amount of blocks a player can send
  # Bypass with permission: 'q.gpcb.transfer.max.bypass'
  # Override with permission:'q.gpcb.transfer.max.<amount>'
  # Default: -1 || Range: 1 - 2147483647 || Use '-1' to disable
  max-claim-blocks: 2147483647

##################################################################
# +------------------------------------------------------------+ #
# |                          Economy                           | #
# +------------------------------------------------------------+ #
##################################################################

# Requires an Economy Provider that supports Vault (ie. EssentialsX, CoinsEngine, etc.)
# Requires Vault: https://www.spigotmc.org/resources/vault.34315/
economy:
  # Note: A server restart is required to enable/disable the economy hook
  # Fee and tax settings can be updated using '/claimblocks reload' or in-game editor
  enabled: true
  # Flat amount that gets charged to the player's account
  fee:
    # Bypass with permission: 'q.gpcb.withdraw.fee.bypass'
    # Override with permission:'q.gpcb.withdraw.fee.<amount>'
    # Default: 0 || Range: 0 - 2147483647 || Use '-1' to disable
    withdraw: -1
    # Bypass with permission: 'q.gpcb.transfer.fee.bypass'
    # Override with permission:'q.gpcb.transfer.fee.<amount>'
    # Default: 0 || Range: 0 - 2147483647 || Use '-1' to disable
    transfer: -1
  # Percentage (based on amount of claim blocks) amount that gets charged
  tax:
    # Bypass with permission: 'q.gpcb.withdraw.tax.bypass'
    # Override with permission:'q.gpcb.withdraw.tax.<amount>'
    # Default: 5 || Range: 0 - 100 || Use '-1' to disable
    withdraw: 5
    # Bypass with permission: 'q.gpcb.transfer.tax.bypass'
    # Override with permission:'q.gpcb.transfer.tax.<amount>'
    # Default: -1 || Range: 0 - 100 || Use '-1' to disable
    transfer: -1