############################################################
# +------------------------------------------------------+ #
# |                   qGP-Trade Config                   | #
# |   Source:   https://github.com/QarthO/qGP-Trade      | #
# |   Download: https://modrinth.com/plugin/qGP-Trade/   | #
# |   Donate:   https://quartzdev.gg/donate              | #
# |   Discord:  https://quartzdev.gg/discord             | #
# +------------------------------------------------------+ #
############################################################
# Default Config
schema-version: 1.0

# Requires 'qgptrade.admin.updates' permission to be notified (or OP)
# Only checks when the server boots or someone with the perm logs in
check-updates: true

############################################################
# +------------------------------------------------------+ #
# |                       Withdraw                       | #
# +------------------------------------------------------+ #
############################################################

# requires permission: 'qgptrade.command.withdraw'
withdraw:
  # The minimum amount of blocks a player can withdraw into a deposit slip
  min-claim-blocks: 100

  # The maxmimum amount of blocks a player can withdraw into a deposit slip
  # Use '-1' to disable
  max-claim-blocks: -1

  # Full customization over the deposit slip (aka voucher)
  # Full material list: https://jd.papermc.io/paper/1.20/org/bukkit/Material.html
  # Supports MiniMessage format: https://docs.advntr.dev/minimessage/format.html
  deposit-slip:
    material: PAPER
    name: "<yellow><bold><blocks> Claim Blocks"
    lore:
      - "Claimblocks: <blocks>"
      - "Withdrawer: <withdrawer>"
      - "ID: <id>"

############################################################
# +------------------------------------------------------+ #
# |                      Transfer                        | #
# +------------------------------------------------------+ #
############################################################

# requires permission: 'qgptrade.command.transfer'
send:
  # The minimum amount of blocks a player can send
  min-claim-blocks: 100

  # The maxmimum amount of blocks a player can send
  # Use '-1' to disable
  max-claim-blocks: -1

############################################################
# +------------------------------------------------------+ #
# |                       Economy                        | #
# +------------------------------------------------------+ #
############################################################

# Requires Vault: https://www.spigotmc.org/resources/vault.34315/
economy:
  enabled: true
  tax:
    withdraw-percentage: 5
    send-percentage: -1