name: qGP-ClaimBlocks
version: '${project.version}'
main: gg.quartzdev.qgpclaimblocks.QGPClaimBlocks
api-version: "1.20"
dependencies:
  server:
    GriefPrevention:
      load: BEFORE
      required: true
    Vault:
      load: BEFORE
      required: false